initial-color-theme=light
[colors-light]
foreground=4c114e
background=e5cece

# Normal colors (0-7)
regular0=e5cece  # base00
regular1=e122a4  # base08
regular2=637e35  # base0B
regular3=9b6800  # base0A
regular4=4527f2  # base0D
regular5=7901cb  # base0E
regular6=147e7f  # base0C
regular7=4c114e  # base05

# Bright colors (8-15)
bright0=a54da5   # base03
bright1=9b0877   # base09
bright2=ccadcc   # base01
bright3=b273b9   # base02
bright4=703170   # base04
bright5=2a0834   # base06
bright6=b101a9   # base0F
bright7=100013   # base07

[main]
font=Fantasque Sans Mono:size=10
letter-spacing=-0.5
#dpi-aware=yes
pad=15x15 center
selection-target=both
#initial-window-size-pixels=880x820

[bell]
urgent=yes
notify=yes

[cursor]
style=underline
unfocused-style=hollow
blink=yes
blink-rate=500
