set nocompatible

syntax enable
set nu
set showcmd
set ignorecase
set smartcase
set incsearch
set hlsearch
set mouse=a
"set tw=80
"set colorcolumn=80

let g:solarized_termtrans=1
set t_Co=16
set background=dark " dark | light "
colorscheme solarized
filetype plugin indent on
set cursorline

call togglebg#map("<F5>")

if has('gui_running')
	set guifont=Source\ Code\ Pro\ Medium\ 10
	set guioptions-=T
endif
if filereadable($HOME . "/.vim/vimrc.local")
	source ~/.vim/vimrc.local
endif
