set nocompatible ruler laststatus=2 showcmd showmode number
set incsearch ignorecase smartcase hlsearch
set title
set shortmess+=I
"set breakindent
syntax enable
set backspace=indent,eol,start

"set foldcolumn=2 foldmethod=syntax foldlevel=99 foldenable

set mouse=a
"set tw=80
set colorcolumn=81

if $USER != 'root'
	set modeline modelines=5
else
	set nomodeline
endif 

let g:solarized_termtrans=1
set t_Co=16
set background=dark " dark | light "
colorscheme solarized
filetype plugin indent on
set cursorline

call togglebg#map("<F5>")

au FileType c,h,java,js setlocal mps+==:;
au FileType c,h setlocal cindent

if has('gui_running')
"	set guifont=Source\ Code\ Pro\ Medium\ 10
	set guicursor+=a:blinkon0
	set guioptions-=m
	set guioptions-=r
	set guioptions-=T
endif
if filereadable($HOME . "/.vim/vimrc.local")
	source ~/.vim/vimrc.local
endif
