set nocompatible ruler laststatus=2 showcmd noshowmode number
set incsearch ignorecase smartcase hlsearch
set title
set shortmess+=I
"set breakindent
execute pathogen#infect()
syntax enable
set backspace=indent,eol,start

"set foldcolumn=2 foldmethod=syntax foldlevel=99 foldenable

set mouse=a
"set tw=80
set colorcolumn=81

if $USER != 'root'
	set modeline modelines=5
else
	set nomodeline
endif 

colorscheme base16-bright
set cursorline

set t_Co=16
filetype plugin indent on


au FileType c,h,java,js setlocal mps+==:;
au FileType c,h setlocal cindent
au FileType pl,perl setlocal sw=4 sts=4 et
au FileType zsh setlocal sw=4 ts=4 et

let g:airline_powerline_fonts=1
let g:airline_theme='base16_bright'

if has('gui_running')
"	set guifont=Source\ Code\ Pro\ Medium\ 10
	set guicursor+=a:blinkon0
	set guioptions-=m
	set guioptions-=r
	set guioptions-=T
endif
if filereadable($HOME . "/.vim/vimrc.local")
	source ~/.vim/vimrc.local
endif
