#!/bin/sh
if pgrep -q -x i3lock; then
	exit 1
fi

imgdir=$(mktemp -d -t locker-${USER})
image=${imgdir}/${USER}_lock.png
image_final=${imgdir}/${USER}_lock_blurred.png

revert() {
	xset dpms 600 600 600
	rm -r "$imgdir"
}

trap revert HUP INT TERM
maim --format=png "$image"
ffmpeg -loglevel quiet -y -i "$image" -vf "gblur=sigma=24" "$image_final"
xset dpms 5 5 5
i3lock -n -e -i "$image_final"
revert
