#!/usr/bin/env perl
use common::sense;

# colours
my %c = (
     '00' => '#272822'
    ,'01' => '#383830'
    ,'02' => '#49483e'
    ,'03' => '#75715e'
    ,'04' => '#a59f85'
    ,'05' => '#f8f8f2'
    ,'06' => '#f5f4f1'
    ,'07' => '#f9f8f5'
    ,red    => '#f92672'
    ,orange => '#fd971f'
    ,yellow => '#f4bf75'
    ,green  => '#a6e22e'
    ,cyan   => '#a1efe4'
    ,blue   => '#66d9fe'
    ,magenta=> '#ae81ff'
    ,brown  => '#cc6633'
);
# glyphs
my %g = (
     batc => '' # charging
    ,batf => '' # full
    ,bath => '' # high
    ,batl => '' # low
    ,bate => '' # empty
    ,mute => '  '
    ,vol  => ''
    ,ws => ''
    ,win => ''
    ,load => ''
    ,wifi => ''
    ,disk => ''
    ,temp => ''
    ,mem  => ''
);
my ($w,$status,$title) = ('','','');
my $pre = "%{l B$c{yellow} F$c{'00'}} $g{ws} ";
my $titlepre="%{B- F$c{orange}} $g{win} %{F$c{'06'} B-}";

my $panel_fifo = ($0 =~ s|[^/]*$||r).'/panel_fifo';
open(my $fifo,'<',$panel_fifo) || die "Failed to open: $!";
$0 = sprintf "lemonstatus: parser (%s)", readlink($panel_fifo); # pretty $0
$|=1;
while(<$fifo>){
    chomp;
    my ($cmd,$args) = split / /,$_,2;
    if ($cmd eq 'SYS') {
        my($load,$space,$ip,$temp,$bat,$battime,$vol,$hwmute,$date,$time)
            = split /\|/,$args,10;

        # LOAD avg (1min)
        $status = $load >= 3 ?
                    "%{B$c{red} F$c{'00'}}"
                  : "%{B$c{'01'} F-}";
        $status .= " $g{load} $load ";
        # disk
        $status .= "%{B$c{'00'} F-}" ;
        $status .= " $g{disk} $space ";
        # BATTERY TODO: states N/U
        $bat =~ /^([CDFNEU]) \((.*)%\)$/;
        if ($1 eq 'D') {      # discharging
            if ($2 >= 60) {
                $status .= "%{B$c{'01'} F-}";
                $status .= " $g{bath}"
            } else {
                $status .= "%{B$c{orange} F$c{'00'}}";
                $status .= " $g{batl}"
            }
        } elsif ($1 eq 'E') { # empty
            $status .= "%{B$c{red} F$c{'00'}}";
            $status .= " $g{bate}"
        } elsif ($1 eq 'C') { # charging
            $status .= "%{B$c{'01'} F".$c{$2 >= 90 ? 'green' : 'orange'}.'}';
            $status .= " $g{batc}"
        } elsif ($1 eq 'F') { # full
            $status .= "%{B$c{'01'} F$c{green}}";
            $status .= " $g{batf}"
        }
        $status .= " $2% ";
        # BATTERY TIME
        $status .= "%{F$c{'03'}}| $battime " if $battime;
        # TEMP
        $status .= $temp >= 45 ?
                     "%{B$c{red} F$c{'00'}}"
                   : "%{B$c{'00'} F-}";
        $status .= " $g{temp} $temp°C ";
        # NETWORK
        if ($ip eq "No Address") {
            $ip = "down";
            $status .= "%{B$c{red} F$c{'00'}}";
        } else {
            $status .= "%{B$c{'01'} F-}";
        }
        $status .= " $g{wifi} $ip ";
        # VOL
        $vol = 0 if $hwmute;
        $status .= "%{B$c{'00'} ";
        $status .= $vol ? "F-} $g{vol}" : "F$c{'red'}} $g{mute}";
        $status .= " $vol% ";
        # DATE & TIME
        $status .= "%{B$c{'01'} F-} $date ";
        $status .= "%{F$c{'02'}}|%{F-} $time ";
    } elsif ($cmd eq 'WSP') {
        $w = $args;
    } elsif ($cmd eq 'WIN') {
        $args =~ s/%/%%{}/g;
        $title = $args unless $title eq $args;
    } else { print STDERR "parser: skipped $cmd $args\n" }

    print $pre,$w,$titlepre,$title,"%{r}",$status,"%{B-}\n"
}
