#!/usr/bin/env zsh
ghetty() {
  if [[ -z "$1" ]]; then
    print "usage: $0 file [channel] [caption]"
    print "\t$0 -l/-channels for a list of channels"
    return 1
  elif [[ "$1" =~ ^-(l|-?chan) ]]; then
    curl -sSf https://images.ghetty.space/channels | tr -d '\[\]"'
    return 0
  fi
  mime=$(file -b --mime-type "$1")
  caption="${@:3}"
  curl -sSf 'https://images.ghetty.space/upload' \
    --http1.1 \
    -F"caption=${caption:-}" \
    -F"channel=#$2" \
    -F"file=@$1;type=$mime"
}
