#!/usr/bin/env zsh
typeset -U path
[[ -d $HOME/bin ]] && path=($HOME/bin $path)
[[ -d $HOME/.zsh/functions ]] && fpath=($HOME/.zsh/functions $fpath)
[[ -r $HOME/.zsh/zshrc.local ]] && source $HOME/.zsh/zshrc.local
[[ -d $HOME/.zsh/zshrc.d ]] && for x in $HOME/.zsh/zshrc.d/*.zsh; do source $x; done
